run:
	sbcl --load quicklisp.lisp --eval '(ql:quickload "mylab")' --load test/mylib-test.lisp --quit

repl:
	sbcl --load quicklisp.lisp

build:
	sbcl --load quicklisp.lisp --eval '(ql:quickload "mylab")' --quit
